# Generated by Django 3.0.6 on 2020-06-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200601_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
