# Generated by Django 3.0.6 on 2020-06-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_bookrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklink',
            old_name='book_link',
            new_name='book_link_djvu',
        ),
        migrations.AddField(
            model_name='book',
            name='count_of_pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booklink',
            name='book_link_fb2',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='booklink',
            name='book_link_mobi',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='booklink',
            name='book_link_pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
    ]
