# Generated by Django 3.0.6 on 2020-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_info_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='answer_state',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='type',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
