# Generated by Django 3.0.6 on 2020-06-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20200615_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bufferfiles',
            name='book',
        ),
        migrations.AddField(
            model_name='bufferfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='buffer/', verbose_name=''),
        ),
    ]
