# Generated by Django 3.0.6 on 2020-07-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20200615_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrating',
            name='like',
        ),
    ]
