# Generated by Django 3.0.6 on 2020-07-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20200709_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrating',
            name='view',
            field=models.IntegerField(default=False),
        ),
    ]
