# Generated by Django 3.1.4 on 2020-12-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_auto_20201215_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfiles',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_a', to='index.book'),
        ),
    ]
