# Generated by Django 3.1.4 on 2020-12-15 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_auto_20201215_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfiles',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_file', to='index.book'),
        ),
    ]
